dist: trusty
notifications:
    email:  false


language: python

python:
  - 2.7


cache:
  - apt
  - pip

sudo: required

addons:
  postgresql: 9.3
  apt:
      packages:
      - libxml2-dev
      - libpq-dev
      - openjdk-7-jdk
      - python-dev
      - postgresql-9.3-postgis-2.3
      
services:
  - postgresql
  - elasticsearch
  
before_install:
  - curl -O https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.4.1.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.1.deb && sudo service elasticsearch restart
  - psql -d postgres -c "ALTER USER postgres with encrypted password 'postgis';"
  - echo "*:*:*:postgres:postgis" >> ~/.pgpass
  - psql -d postgres -c "SET standard_conforming_strings = off;"
  - psql -d postgres -c "CREATE EXTENSION postgis;"

install: 
  - python setup.py install
  - pip install -r arches/install/requirements.txt
  
before_script:
  - sleep 10
  
script: python manage.py test tests --pattern="*.py" --settings="tests.test_settings" 
 
