version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: arches/install/arches_stop.sh
      timeout: 300
      mode: 755
      runas: ubuntu
  BeforeInstall:
    - location: arches/install/ubuntu_xenial_setup.sh
      timeout: 300
      mode: 755
      runas: ubuntu
    - location: arches/install/install_arches.sh
      timeout: 10000
      mode: 755
      runas: ubuntu
    - location: arches/install/update_docs.sh
      timeout: 300
      mode: 755
      runas: ubuntu
  ApplicationStart:
    - location: arches/install/arches_start.sh
      timeout: 300
      mode: 755
      runas: ubuntu
